// preprocessor/output/svelte/src/components/MyComponent.svelte
<script>
  export let message;

  let name = "Hasan";
  let count = 0;
</script>

<div>
  <p>{message || "Hello"} {name}! I can run in React, Vue, Solid or Svelte!</p>
  <button
    on:click={(event) => {
      name = "Ali";
    }}>Click me</button
  >
  <p>Count: {count}</p>
  <button
    on:click={(event) => {
      count = (prev) => prev + 1;
    }}>Increment</button
  >
</div>

// preprocessor/output/react/src/components/MyComponent.jsx
import * as React from "react";
import { useState } from "react";

export default function MyBasicComponent(props) {
  const [name, setName] = useState(() => "Hasan");

  const [count, setCount] = useState(() => 0);

  return (
    <div>
      <p>
        {props.message || "Hello"}
        {name}! I can run in React, Vue, Solid or Svelte!
      </p>

      <button onClick={(event) => setName("Ali")}>Click me</button>

      <p>
        Count:
        {count}
      </p>

      <button onClick={(event) => setCount((prev) => prev + 1)}>
        Increment
      </button>
    </div>
  );
}
